server:
  servlet:
    contextPath: /formidex/v1
spring:
  profiles:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
SONAR_TOKEN: b4f46c920e3f62cac2ca5894a08a8eaaf6b8be0d
sonar:
  projectKey: Thabang-D3v_FormidexProject
  organization: thabang-d3v

#  mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar  -Dsonar.projectKey=Thabang-D3v_FormidexProject -Dsonar.organization=thabang-d3v -Dsonar.sources=src -Dsonar.language=java -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b4f46c920e3f62cac2ca5894a08a8eaaf6b8be0d
#  mvn clean verify sonar:sonar -Dsonar.projectKey=Thabang-D3v_FormidexProject -Dsonar.organization=thabang-d3v -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b4f46c920e3f62cac2ca5894a08a8eaaf6b8be0d
#  mvn clean verify sonar:sonar -Dsonar.token=b4f46c920e3f62cac2ca5894a08a8eaaf6b8be0d -Dsonar.organization=thabang-d3v  -Dsonar.projectKey=Thabang-D3v_FormidexProject